/**
 * Bundled English pools (spec §9.7): curated word/hint entries for Impostor
 * and prompts for Complete the Funny, shipped with the app (no server-side
 * generation). Expand freely; entries must be hand-checked so each hint hints
 * at exactly its word without containing it — hints should be evocative and
 * slightly sideways, never a definition, so crewmate answers still sound
 * plausible from an impostor who only knows the hint.
 */
import type { WordEntry } from "./impostor";

export const IMPOSTOR_WORD_POOL: WordEntry[] = [
  { word: "Sushi", hint: "Asian Cuisine" },
  { word: "Tacos", hint: "Street Food" },
  { word: "Espresso", hint: "Morning Beverage" },
  { word: "Croissant", hint: "Baked Good" },
  { word: "Avocado", hint: "Trendy Food" },
  { word: "Jalapeño", hint: "Spicy Ingredient" },
  { word: "Waffle", hint: "Breakfast Item" },
  { word: "Milkshake", hint: "Sweet Treat" },
  { word: "Pomegranate", hint: "Fruit" },
  { word: "Mozzarella", hint: "Cheese" },
  { word: "Platypus", hint: "Mammal" },
  { word: "Chameleon", hint: "Reptile" },
  { word: "Penguin", hint: "Flightless Bird" },
  { word: "Tarantula", hint: "Creepy Crawler" },
  { word: "Dolphin", hint: "Marine Life" },
  { word: "Mosquito", hint: "Annoying Insect" },
  { word: "Cactus", hint: "Desert Plant" },
  { word: "Venus Flytrap", hint: "Carnivorous Plant" },
  { word: "Coral Reef", hint: "Ocean Ecosystem" },
  { word: "Avalanche", hint: "Natural Disaster" },
  { word: "Astronaut", hint: "STEM Career" },
  { word: "Chef", hint: "Hospitality Job" },
  { word: "Detective", hint: "Investive Role" },
  { word: "Magician", hint: "Entertainer" },
  { word: "Surgeon", hint: "Medical Profession" },
  { word: "Plumber", hint: "Tradesperson" },
  { word: "DJ", hint: "Music Industry" },
  { word: "Lifeguard", hint: "Emergency Responder" },
  { word: "Referee", hint: "Sports Official" },
  { word: "Librarian", hint: "Educational Role" },
  { word: "Microscope", hint: "Scientific Instrument" },
  { word: "Telescope", hint: "Optical Device" },
  { word: "Drone", hint: "Remote-Controlled Tech" },
  { word: "Harmonica", hint: "Musical Instrument" },
  { word: "Chopsticks", hint: "Eating Utensil" },
  { word: "Boomerang", hint: "Throwing Toy" },
  { word: "Stethoscope", hint: "Doctor's Tool" },
  { word: "Compass", hint: "Navigational Aid" },
  { word: "Typewriter", hint: "Vintage Office Equipment" },
  { word: "Parachute", hint: "Aviation Safety Gear" },
  { word: "Colosseum", hint: "Historic Ruins" },
  { word: "Antarctica", hint: "Extreme Environment" },
  { word: "Rollercoaster", hint: "Theme Park Attraction" },
  { word: "Escape Room", hint: "Group Activity" },
  { word: "Scuba Diving", hint: "Water Sport" },
  { word: "Bowling", hint: "Indoor Game" },
  { word: "Podcast", hint: "Audio Entertainment" },
  { word: "Aquarium", hint: "Tourist Attraction" },
  { word: "Submarine", hint: "Watercraft" },
  { word: "Igloo", hint: "Traditional Shelter" },
  { word: "Minecraft", hint: "Sandbox Game" },
  { word: "Fortnite", hint: "Battle Royale Game" },
  { word: "Pokémon", hint: "Monster-Catching Franchise" },
  { word: "Among Us", hint: "Multiplayer Deception Game" },
  { word: "Tetris", hint: "Classic Puzzle Game" },
  { word: "The Legend of Zelda", hint: "Fantasy Adventure Game" },
  { word: "Super Smash Bros.", hint: "Crossover Fighting Game" },
  { word: "Controller", hint: "Gaming Hardware" },
  { word: "Twitch", hint: "Live Streaming Platform" },
  { word: "Virtual Reality", hint: "Immersive Tech" },
  { word: "Esports", hint: "Competitive Gaming" },
  { word: "Respawn", hint: "In-Game Mechanic" },
  { word: "Loot Box", hint: "Digital Reward System" },
  { word: "TikTok", hint: "Social Media App" },
  { word: "Meme", hint: "Viral Internet Trend" },
  { word: "Emoji", hint: "Digital Communication Tool" },
  { word: "Anime", hint: "Japanese Media" },
  { word: "Cosplay", hint: "Fandom Activity" },
  { word: "Lightsaber", hint: "Fictional Weapon" },
  { word: "Hogwarts", hint: "Fictional School" }
];

export const CTF_PROMPT_POOL: string[] = [
  // ── Absurd hypotheticals ─────────────────────────────────────────────
  "The worst thing to overheat",
  "A very bad use for a time machine",
  "The least threatening thing to shout at someone",
  "Something you should never whisper",
  "The worst thing to find under a hat",
  "A terrible slogan for a funeral home",
  "The worst thing to run out of mid-speech",
  "Something a magician should never pull out of a hat",
  "The worst name for a color",
  "A bad thing to be famous for",
  "The most suspicious grocery list item",
  "The worst thing to hear your stomach say",
  "A terrible name for a rescue dog",
  "The worst possible souvenir from the moon",
  "Something you should never buy from a gas station",
  "A horrible thing for a GPS to announce",
  "The worst thing to leave in a will",
  "A bad hobby to mention on a first date",
  "The worst thing to lose at the beach",
  "A terrible way to start a eulogy",
  "The worst answer to a marriage proposal",
  "A terrible subject for a bedtime story",
  "The worst thing to autocorrect to your boss",
  "Something a pirate should never say on a resume",
  "A bad superpower to use at a wedding",
  "The worst thing to teach a parrot",
  "Something you should never microwave",
  "A terrible thing to win at a raffle",
  "The worst thing to stub your toe on at 3am",
  "A bad thing to be allergic to at a petting zoo",
  "The worst flavor of toothpaste",
  "Something you should never store in the fridge",
  "A bad item to bring to a knife fight",
  "The worst thing to misplace at a wedding",
  "A terrible tune to hum in an elevator",
  "The worst thing to slip on",
  "A bad thing to donate to a museum",
  "The worst thing to wear to a job interview",
  "A terrible thing for a scarecrow to say",
  "The worst thing to fall out of your suitcase at customs",
];
